name: 'NetWiz CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  ghdl_sim:
    runs-on: 22.04
    steps:
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: checkout
      uses: actions/checkout@v4
    - name: sim
      working-directory: ./script
      run: bash ghdl_run_all.sh
  
  nvc_sim:
    runs-on: 24.04
    steps:
    - uses: nickg/setup-nvc-ci@v1
      with:
        version: latest
    - name: checkout
      uses: actions/checkout@v4
    - name: sim
      working-directory: ./script
      run: bash nvc_run_all.sh

  document:
    needs: [ghdl_sim, nvc_sim]
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile
          folder: html/html
          target_folder: docs
