name: 'NetWiz CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  ghdl_sim:
    runs-on: ubuntu-latest
    steps:
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: checkout
      uses: actions/checkout@v3
    - name: sim
      working-directory: ./script
      run: bash ghdl_run_all.sh
  # while we wait for the official nvc githib action, we simply install nvc in the GHDL container.
  nvc_sim:
    runs-on: ubuntu-latest
    steps:
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: checkout
      uses: actions/checkout@v3
    # nvc install from source
    - name: clone
      run: git clone https://github.com/nickg/nvc.git
    - name: prepare
      working-directory: ./nvc
      run: ./autogen.sh && mkdir build
    - name: update 
      run: sudo apt-get install build-essential automake autoconf flex check llvm-dev pkg-config zlib1g-dev libdw-dev libffi-dev libzstd-dev
    - name: compile
      working-directory: ./nvc/build
      run: ../configure && make && sudo make install
    # simulate
    - name: sim
      working-directory: ./script
      run: bash nvc_run_all.sh
  document:
    needs: [ghdl_sim, nvc_sim]
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile
          folder: html/html
          target_folder: docs
