name: 'NetWiz CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  ghdl_sim:
    runs-on: ubuntu-22.04
    steps:
    - name: install_ghdl
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc clang libgnat-10 libllvm14 libc-dev zlib1g-dev 
        sudo apt-get install -y wget libglib2.0-0
        wget https://github.com/ghdl/ghdl/releases/download/v4.1.0/ghdl-gha-ubuntu-22.04-llvm.tgz
        sudo tar zxf ghdl-gha-ubuntu-22.04-llvm.tgz -C /usr
        ghdl --version
    - name: checkout
      uses: actions/checkout@v4
    - name: sim_ghdl
      working-directory: ./script
      run: |
        echo $PATH
        pwd
        ls -al ../..
        bash ghdl_run_all.sh
  
  nvc_sim:
    runs-on: ubuntu-latest
    steps:
    - uses: nickg/setup-nvc@v1
      with:
        version: latest
    - name: checkout
      uses: actions/checkout@v4
    - name: sim_nvc
      working-directory: ./script
      run: bash nvc_run_all.sh

  document:
    needs: [ghdl_sim, nvc_sim]
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile
          folder: html/html
          target_folder: docs
