name: 'NetWiz CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: checkout
      uses: actions/checkout@v3
    - name: sim
      working-directory: ./script
      run: bash ghdl_run_all.sh
  document:
    needs: simulate
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile
          folder: docs
